name: Deploy LUMORA to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload LUMORA website
        uses: actions/upload-pages-artifact@v4
        with:
          path: './Web-Development-Level-1-Landing-Page/LUMORA'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4